// Action types
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_LOADING = 'GET_RECIPES_LOADING';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAILURE = 'GET_RECIPES_FAILURE';

export const SET_DARK_MODE = 'SET_DARK_MODE';
